Create SPIDER_QUEENS_STINGER.json
Moulberry/NotEnoughUpdates-REPO pull request #432
Opened 2021-03-11 21:07 UTC by ZviWolf

Added Spider Queen's Stinger (1st time doing this so might be fked up)

2021-03-11 22:19 UTC, DeDiamondPro requested changes
You just need to do some small changes and then you will be fine

2021-03-11 22:19 UTC, DeDiamondPro commented on items/SPIDER_QUEENS_STINGER.json
> +  "modver": "1.0.0",
Mod version should be 2.0.0-REL

2021-03-11 22:19 UTC, DeDiamondPro commented on items/SPIDER_QUEENS_STINGER.json
> +  "nbttag": "{Unbreakable:1,HideFlags:254,display:{Lore:[0:\"§7Damage: §c+180\",2:\"§7Arrows shot using this bow have\",3:\"§7an aura around them that deals\",4:\"§c835.2❁ Damage §7to nearby\",5:\"§7
You forgot to escape the “ at the very end before the double } escape that ( add ) and you should be good

2021-03-12 01:02 UTC, IRONM00N commented
I fixed it for you.

2021-03-12 01:03 UTC, merged