add wand of atonement
Moulberry/NotEnoughUpdates-REPO pull request #442
Opened 2021-03-15 19:16 UTC by fireflame606

hello mr moon

2021-03-15 19:38 UTC, DeDiamondPro commented
Why did you create a new pr, just add it to your other one next time

2021-03-16 18:39 UTC, fireflame606 commented
too many rods in this game ill do some more later

2021-03-17 16:19 UTC, IRONM00N requested changes
Looks good other than the duplicate mod version

2021-03-17 16:19 UTC, IRONM00N commented on items/FARMER_ROD.json
> +  "modver": "2.0.0-REL",
Why are there 2 of these?

2021-04-05 22:29 UTC, closed without merging