Add recipe to Soulflow
Moulberry/NotEnoughUpdates-REPO pull request #559
Opened 2021-07-21 06:09 UTC by ENORMOUZ

Soulflow recipe is: 160x Raw Soulflow

2021-07-21 09:44 UTC, jani270 requested changes

2021-07-21 09:44 UTC, jani270 commented on items/SOULFLOW.json
>    "clickcommand": "",
You forgot to add "viewrecipe", here

2021-07-21 09:57 UTC, ENORMOUZ commented on items/SOULFLOW.json
>    "clickcommand": "",
Fixed.

2021-07-22 13:57 UTC, IRONM00N approved these changes
lgtm

2021-07-22 13:57 UTC, merged