Newest Even Newer New Crystal Hollow Items, this time with a new amazing weird pet that needs to be forged for way too long
Moulberry/NotEnoughUpdates-REPO pull request #567
Opened 2021-07-27 20:26 UTC by Strebbypatty

This will prob be the last new stuff for crystal hollows sadly, so no more epic titles of it after this

2021-07-27 20:28 UTC, Strebbypatty commented
The pet takes 12 days to forge as you may see so don't merge yet please mr. IRONM00N, I will add all rarities and stats hopefully once thats done.

2021-07-27 20:28 UTC, jani270 requested changes
Me when not updated nbt data

2021-07-27 20:28 UTC, jani270 commented on items/AMMONITE;0.json
> +  "nbttag": "{overrideMeta:1b,HideFlags:254,SkullOwner:{Id:\"d05d927e-f686-323e-9c21-a99d0e0cc2ca\",Properties:{textures:[0:{Value:\"ewogICJ0aW1lc3RhbXAiIDogMTYyMDExNTI5NDE1NiwKICAicHJvZmlsZUlkIiA6IC
You forgot to update NBT Data here.

2021-07-27 20:28 UTC, jani270 commented on items/GEMSTONE_CHAMBER.json
> +  "nbttag": "{overrideMeta:1b,HideFlags:254,SkullOwner:{Id:\"558648c0-4dda-371c-87d8-f983a7bc58ca\",Properties:{textures:[0:{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3
You forgot to update NBT Data here. v2

2021-07-27 20:32 UTC, Strebbypatty commented
> Me when not updated nbt data

My brain is too big

2021-07-27 20:32 UTC, DeDiamondPro commented
Bald

2021-07-27 20:37 UTC, jani270 approved these changes
👍

2021-07-28 09:22 UTC, DeDiamondPro approved these changes
epic

2021-07-28 21:06 UTC, IRONM00N approved these changes
lgtm

2021-07-28 21:06 UTC, merged