Add recipes to some more items
Moulberry/NotEnoughUpdates-REPO pull request #578
Opened 2021-08-03 04:29 UTC by ENORMOUZ

2021-08-04 02:58 UTC, ENORMOUZ commented
Will add bieestery command afteer this pull request is pushed to main

2021-08-04 05:13 UTC, ENORMOUZ commented
oops

2021-08-04 18:26 UTC, jani270 requested changes

2021-08-04 18:26 UTC, jani270 commented on items/VENOMS_TOUCH.json
>    "clickcommand": "",
you forgot the viewrecipe command here

2021-08-05 00:59 UTC, ENORMOUZ commented on items/VENOMS_TOUCH.json
>    "clickcommand": "",
oops, fixing.

2021-08-07 18:06 UTC, IRONM00N approved these changes

2021-08-07 18:06 UTC, merged