Various fixes/additions
Moulberry/NotEnoughUpdates-REPO pull request #592
Opened 2021-08-10 16:51 UTC by Eejit43

Yay, GitHub finally works again!

2021-08-10 16:59 UTC, jani270 requested changes

2021-08-10 16:59 UTC, jani270 commented on PET_SKIN_WOLF.json
> +  "nbttag": "{overrideMeta:1b,HideFlags:254,SkullOwner:{Id:\"be4a9ed9-609c-32ea-b49b-44a7bd7ab0f2\",Properties:{textures:[0:{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3
You didnt remove the UUID and Timestamp here

2021-08-10 16:59 UTC, jani270 commented on items/WISHING_COMPASS.json
> +  "nbttag": "{HideFlags:254,SkullOwner:{Id:\"b79aa74e-f5ac-3d6b-a9a8-169b227f9699\",Properties:{textures:[0:{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleH
You didnt remove the UUID and Timestamp here

2021-08-10 16:59 UTC, jani270 commented on items/REFINED_DIAMOND.json
> -    "§5§lEPIC",
Why did you remove the recipe, its still a forge item

2021-08-10 17:11 UTC, Eejit43 commented
Should be fixed, sorry!

2021-08-10 17:50 UTC, jani270 requested changes

2021-08-10 17:50 UTC, jani270 commented on items/REFINED_DIAMOND.json
> +    "",
Line 16 and 17 are not needed

2021-08-10 17:54 UTC, Eejit43 commented
Alright, all should be good now, sorry that took so many attempts...

2021-08-10 18:04 UTC, jani270 approved these changes
Seems fine

2021-08-15 00:31 UTC, IRONM00N approved these changes
I think it looks good, too lazy to test tho so I hope nothing breaks

2021-08-15 00:31 UTC, merged