added pet item
Moulberry/NotEnoughUpdates-REPO pull request #602
Opened 2021-08-22 19:42 UTC by Stekerser

2021-08-22 20:03 UTC, jani270 requested changes

2021-08-22 20:03 UTC, jani270 commented on constants/parents.json
> +    "PET_ITEM_FARMING_SKILL_BOOST_UNCOMMON",
????

2021-08-22 20:04 UTC, jani270 commented
and where do you get that item

2021-08-22 20:23 UTC, Stekerser commented
quest on farming island

2021-08-22 20:24 UTC, Stekerser commented
![2021-08-22 232416](https://user-images.githubusercontent.com/72933528/130369055-756161e3-63ff-4644-8622-5ad87b18bf65.jpg)

2021-08-23 21:41 UTC, jani270 approved these changes

2021-08-23 22:15 UTC, IRONM00N approved these changes

2021-08-23 22:15 UTC, merged