Added rainbow enchant t3
Moulberry/NotEnoughUpdates-REPO pull request #989
Opened 2023-09-24 10:19 UTC by j10a1n15

The book bundle was added, but the enchanted book itself not
![image](https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/assets/45315647/96ac7196-8a0a-42df-bfd9-b828722f9b56)

2023-09-24 10:23 UTC, jani270 requested changes
Please add it to the correct parent and format the file with the ingame save option again.

2023-09-24 10:23 UTC, jani270 commented on items/RAINBOW;3.json
> +      "§9Rainbow II",
Rainbow II Moment

2023-09-24 10:28 UTC, jani270 commented
Oh and please change your branch to master.

2023-09-24 11:29 UTC, j10a1n15 commented
> Please add it to the correct parent and format the file with the ingame save option again.

I would love to format it, but I crash when trying to open the ingame editor

```
java.lang.NullPointerException: Updating screen events
	at io.github.moulberry.notenoughupdates.itemeditor.NEUItemEditor.<init>(NEUItemEditor.java:93)
	at io.github.moulberry.notenoughupdates.NEUOverlay.keyboardInput(NEUOverlay.java:1183)
	at io.github.moulberry.notenoughupdates.listener.RenderListener.onGuiScreenKeyboard(RenderListener.java:1136)```

2023-09-24 16:02 UTC, jani270 commented
> Oh and please change your branch to master.

.

2023-09-24 18:02 UTC, j10a1n15 commented
I dont really understand, so I switch my branch to master and then? Do I pr from the master branch or what? Whats the difference?

2023-09-24 19:31 UTC, jani270 commented
> I dont really understand, so I switch my branch to master and then? Do I pr from the master branch or what? Whats the difference?

Items that are new/changed should always be pr'ed into the master branch as the prerelease branch is only active for people who are using any 2.1.1 version. The prerelease branch will be updated after a few changes on the master

2023-09-24 19:49 UTC, j10a1n15 commented
I see, thank you!

2023-09-25 15:15 UTC, jani270 commented
Closing in favour of #991

2023-09-25 15:15 UTC, closed without merging